apiVersion: v1
kind: Namespace
metadata:
  name: python-app
---
apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  namespace: python-app
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  namespace: python-app
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-world-python
        image: hello-python-flask:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Never
        ports:
        - containerPort: 5000